"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#568fa0 fg:#a3aed2)\
$directory\
[](fg:#568fa0 bg:#394260)\
$git_branch\
$git_metrics\
[](fg:#394260 bg:#212736)\
$nix_shell\
[ ](fg:#1d2230)\
\n$character"""

right_format = """
$nix_shell$aws(fg:#1d2230)
"""

# continuation_prompt = "[▸▹ ](dimmed white)"

add_newline = true

# [fill]
# symbol = '-'
# style = 'bold green'
# $time\
# [ ](fg:#1d2230)\
# \n$character"""

[directory]
style = "fg:#e3e5e5 bg:#568fa0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
disabled = true
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[git_metrics]
added_style = 'bg:#394260 fg:156'
deleted_style = "bg:#394260 fg:212"
format = '[+$added]($added_style)[/](bg:#394260)[-$deleted]($deleted_style)'
disabled = false

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[aws]
symbol = ""
style = "bg:#212736"
format ='[[ $symbol ($profile )(\[$duration\] )](fg:#df8e1d bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[nix_shell]
format =	'[ $symbol$state]($style)'
style = "bg:#212736"
symbol = " "